
// @ts-ignore: Deno module imports
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0"


const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req: Request) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        // 1. Check Environment Variables
        const geminiKey = Deno.env.get('GEMINI_API_KEY')
        if (!geminiKey) {
            throw new Error("Missing GEMINI_API_KEY environment variable")
        }

        // 2. Parse Request Body
        let requestData
        try {
            requestData = await req.json() as any
        } catch (e) {
            throw new Error("Invalid request body. Expected JSON.")
        }

        const { prompt, context } = requestData

        if (!prompt) {
            return new Response(JSON.stringify({ error: "Prompt is required" }), {
                status: 400,
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            })
        }

        const systemInstruction = `You are an expert legal assistant for a Philippine Water District.
    Your task is to generate a Board Resolution based on the user's request.
    
    Adhere strictly to this structure:
    1. Title: Uppercase, concise, starting with "APPROVING...", "AUTHORIZING...", etc.
    2. WHEREAS clauses: Context and justification. Start each with "WHEREAS,".
    3. RESOLVED clauses: The action taken. Start with "RESOLVED," or "RESOLVED FURTHER,".
    
    Output strictly valid JSON (and NOTHING else) in this format:
    {
      "title": "STRING",
      "resolutionNumber": "STRING (suggest a placeholder if unknown)",
      "seriesYear": NUMBER (current year),
      "whereasClauses": ["STRING", "STRING"],
      "resolvedClauses": ["STRING", "STRING"],
      "description": "STRING (A brief, one-sentence summary of what this resolution is about. e.g. 'A resolution approving the budget for...')"
    }
    
    Do not include markdown formatting like \`\`\`json. Just the raw JSON object.`;

        const fullPrompt = `${systemInstruction}\n\nTask: ${prompt}\nContext: ${context || "None"}`;

        // Direct REST API Call to Gemini 1.5 Flash
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
            {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    contents: [{
                        parts: [{ text: fullPrompt }]
                    }]
                })
            }
        );

        if (!response.ok) {
            const errorData = await response.json() as any;
            console.error("Gemini API Error:", JSON.stringify(errorData));
            throw new Error(`Gemini API Error: ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json() as any;
        console.log("Gemini Raw Response:", JSON.stringify(data));

        const responseContent = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!responseContent) {
            throw new Error("No content generated by AI.");
        }

        // 5. Parse Response
        let parsedResponse
        try {
            // Remove any potential markdown code blocks
            const cleanContent = responseContent.replace(/```json/g, '').replace(/```/g, '').trim();
            parsedResponse = JSON.parse(cleanContent)
        } catch (e) {
            console.error("Failed to parse JSON:", responseContent)
            throw new Error("AI generated invalid JSON. Please try again.")
        }

        // 6. Return Success Response
        return new Response(JSON.stringify(parsedResponse), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 200,
        })

    } catch (error: any) {
        console.error("Edge Function Error:", error)
        return new Response(JSON.stringify({ error: error.message || "Internal Server Error", details: error }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 500,
        })
    }
})
